[phases.setup]
nixPkgs = ["python311", "ffmpeg", "nodejs_20", "git"]

[phases.build]
cmds = [
  "git clone --branch 1.2.1 https://github.com/Brainicism/bgutil-ytdlp-pot-provider.git /app/bgutil-server",
  "cd /app/bgutil-server/server && npm install --legacy-peer-deps canvas && npx tsc"
]

[start]
cmd = "node /app/bgutil-server/server/build/main.js & sleep 3 && python bot.py"
